#!/bin/bash 

echo "-------------------"
echo "Running precommit script."
echo "-------------------"


# Branch logic 

branch=$(git rev-parse --abbrev-ref HEAD)

echo "current branch : $branch"

# checking for develop 

if [ "$branch" == 'develop' ]; then
    ehco "you cant push direclty to develope"
    exit 1
fi

# checking for main

if [ "$branch" == 'main' ]; then
    ehco "you cant push direclty to develope"
    exit 1
fi

git add .

echo "testing last line "

exit 0
